name: aksab_driver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # جعلنا الإصدار يبدأ من 3.1.0 ليتوافق مع معظم بيئات البناء الحديثة
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # مكتبات الفايربيز بإصدارات مستقرة ومتوافقة
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.2
  
  # مكتبات المساعدة والخريطة
  sizer: ^3.1.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
