name: aksab_driver
description: "A new Flutter project for Aksab Drivers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.3

  # UI & Design Tools
  sizer: ^3.1.3
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  lucide_icons: ^0.257.0

  # Location & Maps (Ø¶Ø±ÙˆØ±ÙŠ Ø¬Ø¯Ø§Ù‹ Ù„Ù„Ù…Ù†Ø¯ÙˆØ¨)
  geolocator: ^12.0.0 
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

  # --- ðŸš€ Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„Ø®Ù„ÙÙŠØ© ÙˆØ§Ù„ØªØªØ¨Ø¹ Ø§Ù„Ù…Ø¶Ø§ÙØ© ---
  # Ù‡Ø°Ù‡ Ø§Ù„Ù…ÙƒØªØ¨Ø© ØªØ¶Ù…Ù† Ø¸Ù‡ÙˆØ± Ø¥Ø´Ø¹Ø§Ø± Ø¯Ø§Ø¦Ù… ÙŠÙ…Ù†Ø¹ Ø§Ù„Ù†Ø¸Ø§Ù… Ù…Ù† Ù‚ØªÙ„ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ Ø£Ø«Ù†Ø§Ø¡ Ø§Ù„ØªØªØ¨Ø¹
  flutter_foreground_task: ^5.6.0

  # Utilities & State
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  share_plus: ^10.1.4
  path_provider: ^2.1.3
  http: ^1.6.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/OSMB-bc319d822a17aa9ad1089fc05e7d4e752460f877.geojson
