name: aksab_driver
description: "A new Flutter project for Aksab Drivers - Stable Background Tracking Version."
publish_to: 'none'
version: 1.0.0+3  # ðŸš€ Ø±ÙØ¹Ù†Ø§ Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ø§Ø³ØªØ¹Ø¯Ø§Ø¯Ø§Ù‹ Ù„Ù„Ø±ÙØ¹ Ø§Ù„Ø¬Ø¯ÙŠØ¯

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1
  firebase_crashlytics: ^5.0.7  # âœ… Ø¥Ø¶Ø§ÙØ© Ù…ÙƒØªØ¨Ø© ØªØªØ¨Ø¹ Ø§Ù„Ø£Ø¹Ø·Ø§Ù„

  sizer: ^3.1.3
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  google_fonts: ^8.0.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  lucide_icons: ^0.257.0

  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.3.1
  flutter_local_notifications: ^20.1.0

  provider: ^6.1.2
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  app_settings: ^7.0.0
  share_plus: ^12.0.1
  path_provider: ^2.1.3
  http: ^1.6.0
  fl_chart: ^1.1.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2C3E50"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/OSMB-bc319d822a17aa9ad1089fc05e7d4e752460f877.geojson
